### ISSUE TITLE
UpdateLocalPositionAndRotationMethod unit test should check unity version

### ISSUE THREAD

**Issue by heeen** [microsoft/Microsoft.Unity.Analyzers#263]
#### Bug description
SetLocalPositionAndRotationTests.UpdateLocalPositionAndRotationMethod Fails if unity version is too old

- Version of analyzers assembly: 79a79a9
- Analyzer rule: SetLocalPositionAndRotationTests.UpdateLocalPositionAndRotationMethod
- Error (exception message, type, and callstack where applicable): 
```
[xUnit.net 00:00:03.83]     Microsoft.Unity.Analyzers.Tests.SetLocalPositionAndRotationTests.UpdateLocalPositionAndRotationMethod [FAIL]
  Failed Microsoft.Unity.Analyzers.Tests.SetLocalPositionAndRotationTests.UpdateLocalPositionAndRotationMethod [802 ms]
  Error Message:
   Mismatch between number of diagnostics returned, expected "1" actual "0"

Diagnostics:
    NONE.

Expected: True
Actual:   False
  Stack Trace:
     at Microsoft.Unity.Analyzers.Tests.DiagnosticVerifier.VerifyDiagnosticResults(Diagnostic[] actualResults, DiagnosticAnalyzer analyzer, DiagnosticResult[] expectedResults) in /home/florian/src-misc/roslyn-analyzers/Microsoft.Unity.Analyzers/src/Microsoft.Unity.Analyzers.Tests/Infrastructure/DiagnosticVerifier.cs:line 94
   at Microsoft.Unity.Analyzers.Tests.DiagnosticVerifier.VerifyDiagnosticsAsync(AnalyzerVerificationContext context, String[] sources, DiagnosticAnalyzer analyzer, DiagnosticResult[] expected) in /home/florian/src-misc/roslyn-analyzers/Microsoft.Unity.Analyzers/src/Microsoft.Unity.Analyzers.Tests/Infrastructure/DiagnosticVerifier.cs:line 82
   at Microsoft.Unity.Analyzers.Tests.SetLocalPositionAndRotationTests.UpdateLocalPositionAndRotationMethod() in /home/florian/src-misc/roslyn-analyzers/Microsoft.Unity.Analyzers/src/Microsoft.Unity.Analyzers.Tests/SetLocalPositionAndRotationTests.cs:line 32
--- End of stack trace from previous location ---

Failed!  - Failed:     1, Passed:   291, Skipped:     0, Total:   292, Duration: 7 s - Microsoft.Unity.Analyzers.Tests.dll (net7.0)


```
#### To Reproduce
Steps or code to reproduce the behavior:

1. only have older version of unity installed e.g. 2021.3.5f1

#### Expected behavior
the test should not run

-or-

the test should expect no diagnostic as the method it suggests does not exist

#### Additional context
linux, self built

**Comment by sailro** [comment]
Indeed I hit the same issue recently. I'm going to fix that.
